apiVersion: v1
kind: Secret
metadata:
  name: ntnx-secret
  namespace: kube-system
data:
  # base64 encoded prism-ip:prism-port:admin:password. 
  # E.g.: echo -n "10.6.47.155:9440:admin:mypassword" | base64
  key: MTUuMTUuMTMuMTo5NDQwOmFkbWluOkp1c3RvbmUxLg==
